#!/usr/bin/env python
# coding: utf-8

# In[ ]:


import pygame

blue=(0, 204, 255)
skyblue =(213, 246, 255)
black =(0, 0, 0)
def car(coord, flip, screen, sc=100):
    """
    функция рисует машины
    сoord- координаты
    flip-направление
    sc - характерные размеры
    
    
    """
    obj = pygame.Surface((200, 200), pygame.SRCALPHA)

    pygame.draw.ellipse(obj, black, (0, 45, 30, 10))

    pygame.draw.rect(obj, blue, (5, 30, 180, 30))
    pygame.draw.rect(obj, blue, (35, 0, 80, 30))

    pygame.draw.rect(obj, skyblue, (45, 5, 30, 20))
    pygame.draw.rect(obj, skyblue, (80, 5, 30, 20))

    pygame.draw.circle(obj, black, (45, 60), 15)
    pygame.draw.circle(obj, black, (145, 60), 15)

    obj = pygame.transform.scale(obj, (sc, sc))
    if flip:
        obj = pygame.transform.flip(obj, True, False)
    screen.blit(obj, coord)


def cloud(coord, size, screen):
    """
    функция рисует облака
    cood-координаты цетра облаков
    size-размерность облаков
    """
    obj = pygame.Surface((400, 400), pygame.SRCALPHA)

    pygame.draw.ellipse(obj, (128, 128, 128, 100), (0, 0, 400, 200))

    obj = pygame.transform.scale(obj, (size, size))
    screen.blit(obj, coord)


def house(coord, color, screen, hgt=380):
    """
    функция рисует дома
    cood-координаты вершин прямоугольников
    color-цвета
    hgt-высота
    """
    obj = pygame.Surface((200, 400), pygame.SRCALPHA)

    pygame.draw.rect(obj, color, (0, 0, 100, hgt))

    screen.blit(obj, coord)


pygame.init()
screen = pygame.display.set_mode((500, 700))

screen.fill((0, 0, 0))

pygame.draw.rect(screen, (83, 108, 103), (0, 377, 600, 600))

z1 = pygame.Surface((400, 400), pygame.SRCALPHA)
pygame.draw.rect(z1, (255, 255, 255), (0, 0, 400, 400))
pygame.draw.rect(z1, (208, 208, 208), (2, 2, 496, 396))
screen.blit(z1, (0, 0))

house((-50, 2), (0, 0, 0, 100), screen)
house((0, 50), (0, 0, 0, 100), screen)
house((205, 20), (0, 0, 0, 100), screen)
house((230, 50), (0, 0, 0, 100), screen)
house((280, 4), (0, 0, 0, 50), screen)
house((285, 10), (0, 0, 0, 150), screen)

z2 = pygame.Surface((400, 400), pygame.SRCALPHA)
pygame.draw.rect(z2, (255, 255, 255), (0, 0, 400, 400))
pygame.draw.rect(z2, (208, 208, 208), (2, 2, 496, 396))
screen.blit(z2, (400, 0))

house((400, 0), (0, 0, 0, 200), screen)
cloud((100, 0), 200, screen)
cloud((40, 50), 150, screen)
cloud((300, 50), 30, screen)
cloud((150, 100), 100, screen)

img = pygame.Surface((400, 400), pygame.SRCALPHA)
pygame.draw.rect(img, (255, 255, 255), (0, 0, 400, 400))
pygame.draw.rect(img, (183, 196, 200), (2, 2, 496, 396))
screen.blit(img, (200, 80))

house((380, 120), (111, 145, 138), screen)
house((420, 160), (147, 172, 167), screen)

img1 = pygame.Surface((400, 400), pygame.SRCALPHA)
pygame.draw.rect(img1, (255, 255, 255), (0, 0, 400, 400))
pygame.draw.rect(img1, (183, 196, 200), (2, 2, 396, 396))
screen.blit(img1, (-100, 100))

house((30, 140),(147, 172, 167), screen)
house((250, 120), (209, 219, 217), screen)
house((200, 160), (111, 145, 138), screen)
house((0, 160), (183, 200, 196), screen)

cloud((400, 200), 200, screen)

car((300, 600), False, screen, 200)
car((50, 580),  True, screen, 200)
car((270, 520), True, screen)
car((180, 530), True, screen)
car((0, 520), True, screen)
car((400, 520), True, screen)

light = pygame.Surface((400, 400), pygame.SRCALPHA)
pygame.draw.ellipse(light, (250, 250, 250, 30), (0, 0, 300, 150))
screen.blit(light, (150, 500))

pygame.display.update()

done = True
while done:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            done = False
    pygame.display.flip()

pygame.quit()


# In[ ]:





# In[ ]:




